spring:
  profiles:
    active: dev # 表示开发环境
    #active: test # 表示测试环境
    #active: info
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
seata:
  enable-auto-data-source-proxy: false
