server:
  port: 80
  
spring:
  application:
    name: cloud-consumer-feign
  rabbitmq:
    host: 192.168.56.101
    port: 5672
    username: britton
    password: britton
    publisher-returns: true
    template:
      mandatory: true
    publisher-confirm-type: simple
eureka:
  instance:
    instance-id: ${spring.application.name}
    #访问路径可以显示IP地址
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/ #,http://127.0.0.1:7002/eureka/
#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  readTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  connectTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.geoxus.springcloud.service.PaymentFeignService: debug
